; tests/fixtures/conformance.my — the implementation-independent contract
; (see CLAUDE.md): any future my-lisp implementation — C, HDL, whatever —
; should reproduce these results once it has the seven primitives and
; lambda/def/defmacro right. One flat alist per fixture, one fixture per
; top-level form (read via `read-all`, not one big wrapping list) —
; appending a fixture is just adding one more line at the end, never
; touching a shared closing paren. Values never edited in place. Fact
; keys (expr/expected/error/mode) are the contract itself; tag keys
; (tier/axioms/role/note) are this project's own classification of that
; contract, kept in the same record on purpose (2026-08-09) — my-lisp
; can tell them apart by name without two physically separate files.
((expr . "(quote radio)") (expected . "radio") (tier . 1) (axioms . (G3)) (role . "constitutive"))
((expr . "(atom 'radio)") (expected . "t") (tier . 1) (axioms . (G2)) (role . "constitutive"))
((expr . "(atom '())") (expected . "t") (tier . 1) (axioms . (G2)) (role . "constitutive"))
((expr . "(atom '(radio antenna))") (expected . "()") (tier . 1) (axioms . (G2)) (role . "constitutive"))
((expr . "(eq 'radio 'radio)") (expected . "t") (tier . 1) (axioms . (G1)) (role . "constitutive"))
((expr . "(eq 'radio 'antenna)") (expected . "()") (tier . 1) (axioms . (G1)) (role . "constitutive"))
((expr . "(car '(radio antenna))") (expected . "radio") (tier . 1) (axioms . (G2)) (role . "constitutive"))
((expr . "(cdr '(radio antenna))") (expected . "(antenna)") (tier . 1) (axioms . (G2)) (role . "constitutive"))
((expr . "(cons 'radio '(antenna))") (expected . "(radio antenna)") (tier . 1) (axioms . (G2)) (role . "constitutive"))
((expr . "(cond (() 'wrong) (t 'right))") (expected . "right") (tier . 1) (axioms . (G8)) (role . "constitutive"))
((expr . "(/ 5 6 8 7)") (expected . "5/336") (tier . 2) (axioms . (S1)))
((expr . "(+ (/ 1 3) (/ 1 3))") (expected . "2/3") (tier . 2) (axioms . (S1)))
((expr . "(- 1 (/ 1 3))") (expected . "2/3") (tier . 2) (axioms . (S1)))
((expr . "(* (/ 2 3) (/ 9 4))") (expected . "3/2") (tier . 2) (axioms . (S1)))
((expr . "(- (/ 1 3))") (expected . "-1/3") (tier . 2) (axioms . (S1)))
((expr . "(+ (/ 1 2) 0.25)") (expected . "0.75") (tier . 2) (axioms . (S1)))
((expr . "(eq 3 3)") (expected . "t") (tier . 1) (axioms . (G1)) (role . "constitutive"))
((expr . "(eq 3 4)") (expected . "()") (tier . 1) (axioms . (G1)) (role . "constitutive"))
((expr . "(eq \"radio\" \"radio\")") (expected . "t") (tier . 1) (axioms . (G1)) (role . "constitutive"))
((expr . "(eq \"\\r\" \"r\")") (expected . "()") (tier . 1) (axioms . (G1)) (role . "constitutive") (note . "\\r must be the real carriage-return byte (0x0D), not the letter r — found broken in a real fpga-lisp bug, fixed 2026-08-10"))
((expr . "(cond (() 'first) (() 'second) (t 'third))") (expected . "third") (tier . 1) (axioms . (G8)) (role . "constitutive"))
((expr . "(second '(radio antenna signal))") (expected . "antenna") (tier . 3) (axioms . (G5)))
((expr . "(third '(radio antenna signal))") (expected . "signal") (tier . 3) (axioms . (G5)))
((expr . "(not '())") (expected . "t") (tier . 3) (axioms . (G5)))
((expr . "(not 'radio)") (expected . "()") (tier . 3) (axioms . (G5)))
((expr . "(length '(radio antenna signal))") (expected . "3") (tier . 3) (axioms . (G5)))
((expr . "(length '())") (expected . "0") (tier . 3) (axioms . (G5)))
((expr . "(reverse '(radio antenna signal))") (expected . "(signal antenna radio)") (tier . 3) (axioms . (G5)))
((expr . "(append '(radio) '(antenna signal))") (expected . "(radio antenna signal)") (tier . 3) (axioms . (G5)))
((expr . "(map (lambda (x) (+ x 1)) '(1 2 3))") (expected . "(2 3 4)") (tier . 3) (axioms . (G5)))
((expr . "(filter (lambda (x) (eq x 2)) '(1 2 3 2))") (expected . "(2 2)") (tier . 3) (axioms . (G5)))
((expr . "(reduce (lambda (acc x) (+ acc x)) 0 '(1 2 3 4))") (expected . "10") (tier . 3) (axioms . (G5)))
((expr . "(< 1 2 3)") (expected . "t") (tier . 2) (axioms . ()))
((expr . "(< 1 3 2)") (expected . "()") (tier . 2) (axioms . ()))
((expr . "(> 3 2 1)") (expected . "t") (tier . 2) (axioms . ()))
((expr . "(= 1 1 1)") (expected . "t") (tier . 2) (axioms . ()))
((expr . "(= 1/2 0.5)") (expected . "t") (tier . 2) (axioms . (G1 S1)))
((expr . "(<= 1 1 2)") (expected . "t") (tier . 2) (axioms . ()))
((expr . "(>= 2 2 1)") (expected . "t") (tier . 2) (axioms . ()))
((expr . "(print 42)") (expected . "42") (tier . 2) (axioms . ()))
((expr . "(read \"(+ 1 2)\")") (expected . "(+ 1 2)") (tier . 2) (axioms . (G3)))
((expr . "(eval (read \"(+ 1 2)\"))") (expected . "3") (tier . 2) (axioms . (G3)))
((expr . "(car 5)") (error . "Type") (tier . 1) (axioms . (S2)) (role . "constitutive"))
((expr . "(car '())") (error . "Type") (tier . 1) (axioms . (S2)) (role . "constitutive"))
((expr . "(eq '(1) '(2))") (error . "Type") (tier . 1) (axioms . (S2)) (role . "constitutive"))
((expr . "(undefined-symbol)") (error . "UnknownSymbol") (tier . 1) (axioms . (S2)) (note . "symbol lookup is core semantics (tier 1 explicitly lists \"symbols\"); not actually borderline with tier 2"))
((expr . "(lambda (x))") (error . "Arity") (tier . 2) (axioms . (S2)))
((expr . "(quote a b)") (error . "Arity") (tier . 1) (axioms . (S2)) (role . "constitutive"))
((expr . "(cons 1)") (error . "Arity") (tier . 1) (axioms . (S2)) (role . "constitutive"))
((expr . "(/ 1 0)") (error . "InvalidForm") (tier . 2) (axioms . (S2)))
((expr . "(let ((x 1) (y 2)) (+ x y))") (expected . "3") (tier . 3) (axioms . (G5)))
((expr . "(let* ((x 1) (y (+ x 1))) y)") (expected . "2") (tier . 3) (axioms . (G5)))
((expr . "(equal? '(1 (2 3) 4) '(1 (2 3) 4))") (expected . "t") (tier . 3) (axioms . (G5)))
((expr . "(equal? '(1 2) '(1 2 3))") (expected . "()") (tier . 3) (axioms . (G5)))
((expr . "(eq (lambda (x) x) (lambda (x) x))") (expected . "()") (tier . 2) (axioms . (G1)) (role . "constitutive"))
((expr . "(unify 'a 'a '())") (expected . "()") (tier . 3) (axioms . ()))
((expr . "(unify '(var x) 'a '())") (expected . "((x . a))") (tier . 3) (axioms . ()))
((expr . "(unify '(var x) '(var x) '())") (expected . "()") (tier . 3) (axioms . ()))
((expr . "(unify '(1 (var x) 3) '(1 2 3) '())") (expected . "((x . 2))") (tier . 3) (axioms . ()))
((expr . "(unify '(1 (var x) 3) '(1 2 4) '())") (expected . "fail") (tier . 3) (axioms . ()))
((expr . "(let ((rules '(((parent alice bob))))) (reason '(parent alice bob) rules))") (expected . "((() (proved (parent alice bob) (parent alice bob) ())))") (tier . 3) (axioms . ()))
((expr . "(let ((rules '(((parent alice bob))))) (reason (list 'parent (logic-var 'x) 'bob) rules))") (expected . "((((x . alice)) (proved (parent (var x) bob) (parent alice bob) ())))") (tier . 3) (axioms . ()))
((expr . "(let ((rules '(((bird (var x)) (animal (var x)) (not (penguin (var x)))) ((animal tweety)) ((animal pingu)) ((penguin pingu))))) (reason (list 'bird (logic-var 'x)) rules))") (expected . "(((((x . 0) . tweety) (x var (x . 0))) (proved (bird (var x)) (bird (var (x . 0))) ((proved (animal (var (x . 0))) (animal tweety) ()) (proved-not (penguin (var (x . 0))))))))") (tier . 3) (axioms . ()))
((expr . "(equal? '(p . 0) (cons 'p 0))") (expected . "t") (tier . 1) (axioms . (G2)))
((expr . "(car '(a b . c))") (expected . "a") (tier . 1) (axioms . (G2)) (role . "constitutive"))
((expr . "(cdr (cdr '(a b . c)))") (expected . "c") (tier . 1) (axioms . (G2)) (role . "constitutive"))
((expr . "(unify '(var x) '(f (var x)) '())") (expected . "fail") (tier . 3) (axioms . ()) (note . "occurs-check, principle 3 evidence — prevents building an infinite structure, not a G/S axiom"))
((expr . "(defmacro foo)") (error . "Arity") (tier . 2) (axioms . (S2)) (note . "defmacro validates arity like any other special form"))
((expr . "(defmacro 5 (x) x)") (error . "InvalidForm") (tier . 2) (axioms . (S2)) (note . "defmacro validates its name is a symbol, not just its arity"))
((expr . "(def count-down (lambda (n) (cond ((eq n 0) 'done) (t (count-down (- n 1)))))) (count-down 100000)") (expected . "done") (tier . 2) (axioms . (S3)) (note . "100,000-deep self-tail-call through the real evaluator stays O(1) host-stack usage regardless of recursion depth — previously only exercised by crates/my-lisp/tests/stack_safety.rs (Rust-specific), not the implementation-independent contract; a non-tail-call-optimizing future core would fail here, not just in production"))
((expr . "(map (lambda (x) (+ x 1)) '())") (expected . "()") (tier . 3) (axioms . (G5)) (note . "empty-list edge case, previously untested — map"))
((expr . "(filter (lambda (x) (eq x 2)) '())") (expected . "()") (tier . 3) (axioms . (G5)) (note . "empty-list edge case, previously untested — filter"))
((expr . "(reduce (lambda (acc x) (+ acc x)) 0 '())") (expected . "0") (tier . 3) (axioms . (G5)) (note . "empty-list edge case, previously untested — reduce returns its initial accumulator unchanged"))
((expr . "((lambda (a b . rest) rest) 1 2 3 4 5)") (expected . "(3 4 5)") (tier . 1) (axioms . (G2)) (role . "constitutive") (note . "dotted lambda-list: variadic parameter binding, added 2026-08-09 to let list move out of Rust"))
((expr . "((lambda args args) 1 2 3)") (expected . "(1 2 3)") (tier . 1) (axioms . (G2)) (role . "constitutive") (note . "bare-symbol lambda-list: zero fixed params, every argument bound as one list"))
((expr . "((lambda (a b . rest) a) 1)") (error . "Arity") (tier . 1) (axioms . (S2)) (role . "constitutive") (note . "variadic lambda still enforces its fixed parameters"))
((expr . "(list 1 2 3)") (expected . "(1 2 3)") (tier . 3) (axioms . (G5)) (note . "list moved from a Rust special form to lib/core.my (lambda args args) once variadic parameters existed to express it"))
((expr . "(let ((second (lambda (x) 'shadowed))) (second '(1 2 3)))") (expected . "shadowed") (tier . 2) (axioms . (G4)) (note . "neither Lisp-1 nor Lisp-2 as an identity — ordinary def/defmacro bindings share one namespace and are locally shadowable"))
((expr . "(let ((car (lambda (x) 'shadowed))) (car '(1 2)))") (expected . "1") (tier . 1) (axioms . (G4)) (role . "constitutive") (note . "the seven primitives are syntax, dispatched before any environment lookup, so never shadowable — the same distinction Scheme draws between special forms and procedures"))
((expr . "(reverse '())") (expected . "()") (tier . 3) (axioms . (G5)) (note . "empty-list edge case, previously untested"))
((expr . "(append '() '(a b))") (expected . "(a b)") (tier . 3) (axioms . (G5)) (note . "empty-list edge case, previously untested — empty first argument"))
((expr . "(append '(a b) '())") (expected . "(a b)") (tier . 3) (axioms . (G5)) (note . "empty-list edge case, previously untested — empty second argument"))
((expr . "(symbol? 'radio)") (expected . "t") (tier . 3) (axioms . (G5)) (note . "symbol? is now lib/core.my: derived from atom, write-to-string, string->symbol, and eq rather than Rust type dispatch"))
((expr . "(string? \"radio\")") (expected . "t") (tier . 2) (axioms . ()))
((expr . "(symbol->string 'radio)") (expected . "\"radio\"") (tier . 2) (axioms . ()))
((expr . "(string->symbol \"radio\")") (expected . "radio") (tier . 2) (axioms . ()))
((expr . "(string-first \"radio\")") (expected . "\"r\"") (tier . 2) (axioms . ()))
((expr . "(string-rest \"radio\")") (expected . "\"adio\"") (tier . 2) (axioms . ()))
((expr . "(read-all \"1 2 3\")") (expected . "(1 2 3)") (tier . 2) (axioms . (G3)) (note . "the multi-form counterpart to read — previously tested only in Rust unit tests"))
((expr . "(princ \"raw\")") (expected . "\"raw\"") (tier . 2) (axioms . ()) (note . "princ composes and returns its argument exactly like print — the raw/unquoted transcript output itself is regression-tested in crates/my-lisp/tests/mccarthy.rs since this fixture harness only checks the return value, not the print transcript"))
((expr . "(< 5)") (expected . "t") (tier . 2) (axioms . ()) (note . "a single argument is vacuously ordered, previously untested here"))
((expr . "(defmacro my-list items (cons 'quote (cons items '()))) (my-list 1 2 3)") (expected . "(1 2 3)") (tier . 1) (axioms . (G4)) (role . "constitutive") (note . "variadic defmacro success path — the error paths were already covered, the success path wasn't"))
((expr . "(understand '(earth is a planet))") (expected . "((planet earth))") (tier . 3) (axioms . ()) (note . "lib/understand.my — the controlled-natural-language bridge, previously tested only in Rust unit tests, not the implementation-independent contract"))
((expr . "(understand '(earth orbits sun))") (expected . "((orbits earth sun))") (tier . 3) (axioms . ()) (note . "subject-verb-object relation shape"))
((expr . "(understand '(all planet have mass))") (expected . "((has (var w) mass) (planet (var w)))") (tier . 3) (axioms . ()) (note . "universal-rule shape"))
((expr . "(narrate-fact (car (understand '(earth is a planet))))") (expected . "(earth is a planet)") (tier . 3) (axioms . ()) (note . "lib/narrate.my — the structure-to-text half of the bridge, previously tested only in Rust unit tests"))
((expr . "(equal? '(mars is a planet) (narrate-fact (car (understand '(mars is a planet)))))") (expected . "t") (tier . 3) (axioms . ()) (note . "understand and narrate-fact are direct inverses for the is-a shape"))
((expr . "(cond (0 'truthy) (t 'falsy))") (expected . "truthy") (tier . 1) (axioms . ()) (note . "0 is truthy in my-lisp, unlike C/Python/JS — only Nil and Bool(false) are falsy (Value::is_truthy). Not G8: G8 is narrowly about '() as list/boolean, not a general \"empty-shaped values are false\" rule. Independent of the item-10 exactness redesign — is_truthy never inspects a number's exactness, only Nil/Bool(false)."))
((expr . "(eq 3 3.0)") (expected . "()") (tier . 1) (axioms . (S1)) (note . "PLAN.md item 10, Path A: exactness is part of a number's identity — an exact integer and an inexact real of the same magnitude are different values, so eq (identity/atom equality) tells them apart."))
((expr . "(eq 3 3)") (expected . "t") (tier . 1) (axioms . (S1)) (note . "same exactness, same magnitude"))
((expr . "(eq 3.0 3.0)") (expected . "t") (tier . 1) (axioms . (S1)) (note . "same inexact value both sides"))
((expr . "(= 3 3.0)") (expected . "t") (tier . 1) (axioms . (S1)) (note . "= compares magnitude only, deliberately diverging from eq — 3 and 3.0 are the same mathematical quantity even though they are different values"))
((expr . "(print 3)") (expected . "3") (tier . 2) (axioms . (S1)) (note . "exact integer prints without a decimal point"))
((expr . "(print 3.0)") (expected . "3.0") (tier . 2) (axioms . (S1)) (note . "inexact real always prints with a decimal point, even when whole-valued — the fix for the original bug this item was opened for: (+ 2.0 1.0) used to print as \"3\", silently erasing the written-with-a-decimal-point intent"))
((expr . "(print 3.00)") (expected . "3.0") (tier . 2) (axioms . (S1)) (note . "3.0/3.00/3.000 are the same inexact value regardless of trailing zeros in the literal — canonical print form has exactly one decimal digit for a whole inexact number"))
((expr . "(+ 2.0 1.0)") (expected . "3.0") (tier . 2) (axioms . (S1)) (note . "inexact + inexact -> inexact; this is the exact expression that first exposed the bug (used to evaluate to 3, losing all trace of the decimal points)"))
((expr . "(+ 2.0 1)") (expected . "3.0") (tier . 2) (axioms . (S1)) (note . "exact + inexact -> inexact, one inexact operand contaminates the result"))
((expr . "(+ 2 1)") (expected . "3") (tier . 2) (axioms . (S1)) (note . "exact + exact -> exact, stays a precise integer"))
((expr . "(string-append \"hello, \" \"world\")") (expected . "\"hello, world\"") (tier . 2) (axioms . ()) (note . "PLAN.md item 14 — genuinely needs a Rust primitive, unlike string-length/string-contains? below: no existing primitive combines two strings into a new one"))
((expr . "(string<? \"a\" \"b\")") (expected . "t") (tier . 2) (axioms . ()) (note . "PLAN.md item 15 — the one Rust primitive the persistent-map design needed; ordering, not just equality, can't be derived from string-first/string-rest/eq alone"))
((expr . "(string<? \"b\" \"a\")") (expected . "()") (tier . 2) (axioms . ()))
((expr . "(map-get \"a\" (map-insert \"a\" 1 map-empty))") (expected . "(1)") (tier . 3) (axioms . (G5)) (note . "PLAN.md item 15 — lib/persistent-map.my, an AVL-balanced persistent tree built on cons/car/cdr alone, no mutation; map-get's \"maybe\" shape (() absent, (value) present) avoids confusing a stored () with not-found"))
((expr . "(map-get \"z\" (map-insert \"a\" 1 map-empty))") (expected . "()") (tier . 3) (axioms . (G5)))
((expr . "(string-length \"\")") (expected . "0") (tier . 3) (axioms . (G5)) (note . "PLAN.md item 14/20 — lib/core.my, expressible via string-first/string-rest/eq alone, no new Rust primitive needed"))
((expr . "(string-length \"hello\")") (expected . "5") (tier . 3) (axioms . (G5)))
((expr . "(string-prefix? \"hell\" \"hello\")") (expected . "t") (tier . 3) (axioms . (G5)))
((expr . "(string-prefix? \"world\" \"hello\")") (expected . "()") (tier . 3) (axioms . (G5)))
((expr . "(string-contains? \"ell\" \"hello\")") (expected . "t") (tier . 3) (axioms . (G5)))
((expr . "(string-contains? \"xyz\" \"hello\")") (expected . "()") (tier . 3) (axioms . (G5)))
((expr . "(tcp-connect 42 8099)") (error . "Type") (tier . 2) (axioms . ()) (note . "PLAN.md item 21 — a real listen/accept/connect round trip needs a live network peer, which conformance.my's single-session fixture runner can't provide; only the type-check error path is a pure expression testable this way. See crates/my-lisp/tests/tcp.rs for the live client/server round-trip, run on separate threads with separate Sessions."))
((expr . "(tcp-write \"not a connection\" \"x\")") (error . "Type") (tier . 2) (axioms . ()))
((expr . "(process-run \"git\" '())") (error . "InvalidForm") (tier . 2) (axioms . (S2)) (note . "PLAN.md item 21's follow-up — the default session (this fixture runner's own, and every conformance.my fixture's) never opts into Environment::with_process_allowlist, so process-run always fails named, never runs anything, matching S2. See crates/my-lisp/tests/mccarthy.rs's process_run_* tests for the allowlist opt-in path, which needs a session this single shared fixture-runner session can't provide per-fixture."))
((expr . "(write-file-bytes 42 '(1 2 3))") (error . "Type") (tier . 2) (axioms . ()) (note . "PLAN.md item 22 — a real write-file-bytes/read-file-bytes round trip is a filesystem side effect, which conformance.my's pure-expression fixture runner can't provide; only the type-check error path is testable this way. See crates/my-lisp/tests/mccarthy.rs's write_file_bytes_then_read_file_bytes_round_trips_non_utf8_bytes for the real round trip, including bytes (255, 254) that aren't valid standalone UTF-8 — the exact case write-file (String-based) can't represent."))
((expr . "(write-file-bytes \"path-does-not-matter.bin\" '(1 256 3))") (error . "Type") (tier . 2) (axioms . ()) (note . "PLAN.md item 22 — each byte-list element must be an integer 0-255"))
((expr . "(quotient 17 5)") (expected . "3") (tier . 3) (axioms . (G5)) (note . "surfaced from the fpga-lisp session's assembler.my — lib/core.my, expressible via -, <, and cond alone, no new Rust primitive needed. Scope: non-negative a, positive b only"))
((expr . "(mod 17 5)") (expected . "2") (tier . 3) (axioms . (G5)))
((expr . "(mod 100 10)") (expected . "0") (tier . 3) (axioms . (G5)))
((expr . "(quotient 9999999999999 10)") (expected . "999999999999") (tier . 3) (axioms . (G5)) (note . "regression fixture: the original repeated-subtraction quotient had recursion depth equal to the quotient's VALUE, not its digit count, and overflowed the Rust host's stack on exactly this input while implementing number->string. Fixed 2026-08-10 via a doubling algorithm, O(log(a/b)) depth"))
((expr . "(number->string 9999999999999)") (expected . "\"9999999999999\"") (tier . 3) (axioms . (G5)) (note . "surfaced from the fpga-lisp session's assembler.my, which had its own version limited to ~10 digits by a fixed DECIMAL-POWERS table; this one has no digit-count ceiling of its own"))
((expr . "(number->string 0)") (expected . "\"0\"") (tier . 3) (axioms . (G5)))
((expr . "(quotient 5 0)") (error . "InvalidForm") (tier . 3) (axioms . (G5)) (note . "regression fixture: (quotient a 0) used to hang forever (largest-chunk's doubling never grows from chunk=0) instead of failing named -- fixed 2026-08-10 by routing b=0 through the primitive / for its already-tested division-by-zero error"))
((expr . "(mod 5 0)") (error . "InvalidForm") (tier . 3) (axioms . (G5)))
((expr . "(fourth '(w x y z))") (expected . "z") (tier . 3) (axioms . (G5)) (note . "surfaced from the fpga-lisp session's assembler.my — same single-parameter primitive-chain pattern as second/third, one step deeper"))
((expr . "(nth 2 '(a b c))") (expected . "c") (tier . 3) (axioms . (G5)))
((expr . "(member? 'b '(a b c))") (expected . "t") (tier . 3) (axioms . (G5)))
((expr . "(member? 'q '(a b c))") (expected . "()") (tier . 3) (axioms . (G5)))
((expr . "(assoc 'b '((a . 1) (b . 2) (c . 3)))") (expected . "(b . 2)") (tier . 3) (axioms . (G5)) (note . "generalizes the (symbol . value) alist-lookup shape lib/meta-eval.my's env-lookup already hand-rolls for its own specific case"))
((expr . "(assoc 'q '((a . 1) (b . 2)))") (expected . "()") (tier . 3) (axioms . (G5)))
((expr . "(cddr '(a b c d))") (expected . "(c d)") (tier . 3) (axioms . (G5)) (note . "found duplicated locally in lib/understand.my before being moved to core.my, 2026-08-10"))
((expr . "(eq cadddr fourth)") (expected . "t") (tier . 3) (axioms . (G5)) (note . "cadddr is a literal alias for fourth, same closure object -- lib/reason.my had its own character-for-character-identical local cadddr before this dedup"))
((expr . "(fifth '(v w x y z))") (expected . "z") (tier . 3) (axioms . (G5)) (note . "found duplicated in two places at once: lib/narrate.my's own local fifth (identical), and lib/persistent-map.my's node-right (same operation, no name)"))
((expr . "(+ 123456789012345678901234567890 1)") (expected . "123456789012345678901234567891") (tier . 2) (axioms . (S1)) (note . "bare integer literals use arbitrary precision beyond f64's exact 2^53 range; exact syntax never silently rounds"))
; Canonical serialization law — portable wire-format facts, not Rust snapshots.
((expr . "(write-to-string 'radio)") (expected . "\"radio\"") (tier . 2) (axioms . (G6 S1)) (note . "canonical serialization: readable symbol"))
((expr . "(equal? (read (write-to-string 'radio)) 'radio)") (expected . "t") (tier . 2) (axioms . (G6 S1)) (note . "canonical serialization round-trip: symbol"))
((expr . "(write-to-string \"line\\n\\t\\\"\\\\\")") (expected . "\"\\\"line\\\\n\\\\t\\\\\\\"\\\\\\\\\\\"\"") (tier . 2) (axioms . (G6 S1)) (note . "canonical serialization: string escapes"))
((expr . "(equal? (read (write-to-string \"line\\n\\t\\\"\\\\\")) \"line\\n\\t\\\"\\\\\")") (expected . "t") (tier . 2) (axioms . (G6 S1)) (note . "canonical serialization round-trip: escaped string"))
((expr . "(write-to-string '(alpha beta gamma))") (expected . "\"(alpha beta gamma)\"") (tier . 2) (axioms . (G6 S1)) (note . "canonical serialization: proper list"))
((expr . "(equal? (read (write-to-string '(alpha beta gamma))) '(alpha beta gamma))") (expected . "t") (tier . 2) (axioms . (G6 S1)) (note . "canonical serialization round-trip: proper list"))
((expr . "(write-to-string '(alpha beta . gamma))") (expected . "\"(alpha beta . gamma)\"") (tier . 2) (axioms . (G6 S1)) (note . "canonical serialization: dotted list"))
((expr . "(equal? (read (write-to-string '(alpha beta . gamma))) '(alpha beta . gamma))") (expected . "t") (tier . 2) (axioms . (G6 S1)) (note . "canonical serialization round-trip: dotted list"))
((expr . "(list (write-to-string 42) (write-to-string 10/20))") (expected . "(\"42\" \"1/2\")") (tier . 2) (axioms . (G6 S1)) (note . "canonical serialization: exact integer and reduced rational"))
((expr . "(list (equal? (read (write-to-string 42)) 42) (equal? (read (write-to-string 10/20)) 1/2))") (expected . "(t t)") (tier . 2) (axioms . (G6 S1)) (note . "canonical serialization round-trip: exact numbers"))
((expr . "(list (write-to-string 3.00) (write-to-string 1.25))") (expected . "(\"3.0\" \"1.25\")") (tier . 2) (axioms . (G6 S1)) (note . "canonical serialization: finite inexact numbers"))
((expr . "(list (equal? (read (write-to-string 3.00)) 3.0) (equal? (read (write-to-string 1.25)) 1.25))") (expected . "(t t)") (tier . 2) (axioms . (G6 S1)) (note . "canonical serialization round-trip: finite inexact numbers"))
((expr . "(cond (0 'zero-is-truthy) (t 'wrong))") (expected . "zero-is-truthy") (tier . 1) (axioms . (G8)) (role . "constitutive") (note . "canonical cross-implementation G8 gate: fixnum 0 is truthy; only Nil is the canonical false value"))

((expr . "(-> 10 (+ 2) (* 3))") (expected . "36") (tier . 3) (axioms . (G5)) (note . "thread-first macro (->) unwraps forms recursively"))
((expr . "(->> 10 (+ 2) (* 3))") (expected . "36") (tier . 3) (axioms . (G5)) (note . "thread-last macro (->>) unwraps forms recursively, placing subject last"))
((expr . "(-> 5 (- 2))") (expected . "3") (tier . 3) (axioms . (G5)))
((expr . "(->> 5 (- 2))") (expected . "-3") (tier . 3) (axioms . (G5)))
((expr . "(-> 5)") (expected . "5") (tier . 3) (axioms . (G5)))
((expr . "(->> 5)") (expected . "5") (tier . 3) (axioms . (G5)))
